# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='tags',
            field=models.ManyToManyField(related_name='checklist', to='common.Tag'),
        ),
    ]
